// Generated by CoffeeScript 1.7.1
(function() {
  var config;

  config = {};

  config.redis_host = 'pub-redis-11414.us-east-1-3.3.ec2.garantiadata.com';

  config.redis_port = 11414;

  config.redis_password = 'redisSteam';

  config.mongo_db_host = 'steam_node:steamNode@ds037478.mongolab.com:37478';

  config.mongo_db_name = 'steamdb';

  config.steam_web_api_key = 'F2AB1C25BD33F9E4E3F743E05490CE7C';

  config.steam_web_api_domain = 'nkahnt.com';

  config.steam_web_api_user_api = 'http://api.steampowered.com/IPlayerService/';

  config.steam_web_api_custom_url = 'http://steamcommunity.com/id/';

  config.steam_web_api_id_url = 'http://steamcommunity.com/profiles/';

  config.steam_web_api_64_url = 'http://steamcommunity.com/profiles/';

  config.steam_app_cache_validity = 3600;

  config.steam_user_app_cache_validity = 600;

  config.n_of_app_in_query_batch = 250;

  module.exports = config;

}).call(this);
