// Generated by CoffeeScript 1.7.1
(function() {
  var config;

  config = {};

  config.redis_host = '';

  config.redis_port = 11414;

  config.redis_password = '';

  config.redis_use_ENV = true;

  config.mongo_db_host = '';

  config.mongo_db_name = '';

  config.mongo_use_ENV = true;

  config.steam_web_api_key = '';

  config.steam_web_api_domain = '';

  config.steam_web_api_ENV = true;

  config.steam_web_api_user_api = 'http://api.steampowered.com/IPlayerService/';

  config.steam_web_api_custom_url = 'http://steamcommunity.com/id/';

  config.steam_web_api_id_url = 'http://steamcommunity.com/profiles/';

  config.steam_web_api_64_url = 'http://steamcommunity.com/profiles/';

  config.steam_app_cache_validity = 3600;

  config.steam_user_app_cache_validity = 600;

  config.n_of_app_in_query_batch = 250;

  module.exports = config;

}).call(this);
