// Generated by CoffeeScript 1.7.1
(function() {
  var SteamClient;

  module.exports = function(opts, callback) {
    var s;
    s = this;
    if (!s.redis_client || !s.mongo_client) {
      s.opts = opts;
      s.redis = require("redis");
      s.redis_client = s.redis.createClient(opts.redis_port, opts.redis_host, {
        auth_pass: opts.redis_password
      });
      console.log("Redis connected");
      s.mongo_client = require('mongodb').MongoClient;
      return s.mongo_client.connect("mongodb://" + opts.mongo_db_host + "/" + opts.mongo_db_name, function(err, db) {
        var sClient;
        console.dir("Mongo connected: ", err);
        s.mongo_db = db;
        sClient = new SteamClient(s.redis_client, s.mongo_db, s.opts);
        if ("function" === typeof callback) {
          return callback(null, sClient);
        }
      });
    } else {
      if ("function" === typeof callback) {
        return callback(null, new SteamClient(s.redis_client, s.mongo_db, s.opts));
      }
    }
  };

  SteamClient = (function() {
    SteamClient.prototype.KEYS = {
      STEAM_APPLIST_REFRESH: 'STEAM.APPLIST.REFRESH',
      STEAM_APPLIST_RAW: 'STEAM.APPLIST.RAW',
      STEAM_APP_IDS: 'STEAM.APP_IDS',
      STEAM_APP_SUCCESS_IDS: 'STEAM.APP_SUCCESS_IDS',
      STEAM_METACRITIC_SCORES: 'STEAM.METACRITIC_SCORES',
      MDB_STEAM_APPS: 'steam_apps'
    };

    function SteamClient(redis_client, mongo_db, opts) {
      this.jsonpack = require('jsonpack/main');
      this.opts = opts;
      this.unirest = require("unirest");
      this.xml2js = require("xml2js");
      this.redis_client = redis_client;
      this.mongo_db = mongo_db;
    }

    SteamClient.prototype.get_user_steamId_details = function(user_id, callback) {
      var custom_url, e, s, sid, w;
      s = this;
      if (/^[0-9]{17,25}$/.test(user_id)) {
        custom_url = [s.opts.steam_web_api_64_url + user_id, s.opts.steam_web_api_custom_url + user_id];
      } else {
        custom_url = [s.opts.steam_web_api_custom_url + user_id, s.opts.steam_web_api_64_url + user_id];
      }
      if (sid = /^STEAM_([0-9]{1,10}):([0-9]{1,10}):([0-9]{1,10})$/.exec(user_id)) {
        w = parseInt(sid[3]) * 2 + parseInt(sid[2]);
        custom_url.unshift(s.opts.steam_web_api_id_url + ("[U:1:" + w + "]"));
      }
      e = function(c) {
        return s.unirest.get(custom_url[c]).query({
          xml: 1
        }).end((function(_this) {
          return function(response) {
            return s.xml2js.parseString(response.body, function(err, result) {
              if (!err) {
                if (result.profile) {
                  if ("function" === typeof callback) {
                    return callback(null, {
                      steamID64: result.profile.steamID64,
                      customURL: result.profile.customURL
                    });
                  }
                } else {
                  c++;
                  if (c < custom_url.length) {
                    return e(c);
                  } else {
                    if ("function" === typeof callback) {
                      return callback("Cannot find profile", null);
                    }
                  }
                }
              } else {
                if ("function" === typeof callback) {
                  return callback(err, null);
                }
              }
            });
          };
        })(this));
      };
      return e(0);
    };

    SteamClient.prototype.get_recommendation = function(user_id, callback) {
      var s;
      s = this;
      return s.get_recommendation(user_id, function(err, steams) {
        if (!err) {

        } else {
          if ("function" === typeof callback) {
            return callback(err, null);
          }
        }
      });
    };

    SteamClient.prototype.get_user_owned_games = function(steam_id, callback) {
      var s;
      console.log("get_user_owned_games: " + steam_id);
      s = this;
      return s.get_user_steamId_details(steam_id, function(err, steam_id_result) {
        if (!err) {
          return s.redis_client.GET("USER." + steam_id + ".CACHED_APP", function(err, cached_app_list) {
            if (err || !cached_app_list) {
              console.log("- cache not found, getting owned games list for: " + steam_id);
              return s.unirest.get(s.opts.steam_web_api_user_api + "GetOwnedGames/v0001").query({
                key: s.opts.steam_web_api_key,
                steamid: steam_id_result.steamID64,
                format: "json"
              }).end((function(_this) {
                return function(response) {
                  var appIdInt, app_ids, game, play_time, result, _i, _len, _ref;
                  console.log("- finished getting owned games list for: " + steam_id);
                  result = response.body;
                  if (result && result.response) {
                    if ("function" === typeof callback) {
                      app_ids = [];
                      play_time = {};
                      _ref = result.response.games;
                      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                        game = _ref[_i];
                        appIdInt = parseInt(game.appid);
                        app_ids.push(appIdInt);
                        play_time[appIdInt] = game.playtime_forever;
                      }
                      return s.mongo_db.collection(s.KEYS.MDB_STEAM_APPS).find({
                        _id: {
                          $in: app_ids
                        }
                      }, {
                        name: 1,
                        website: 1,
                        required_age: 1,
                        pc_requirement: 1,
                        mac_requirement: 1,
                        linux_requirement: 1,
                        developers: 1,
                        publishers: 1,
                        price_overview: 1,
                        package_groups: 1,
                        platforms: 1,
                        categories: 1,
                        genres: 1,
                        achievements: 1,
                        release_date: 1,
                        metacritic: 1,
                        header_image: 1
                      }).toArray(function(err, game_details) {
                        var _j, _len1;
                        if ("function" === typeof callback) {
                          for (_j = 0, _len1 = game_details.length; _j < _len1; _j++) {
                            game = game_details[_j];
                            game.playtime_forever = play_time[game._id];
                          }
                          result = {
                            game_count: result.response.game_count,
                            in_db_count: game_details.length,
                            games: game_details
                          };
                          callback(null, result);
                          console.log("- finished getting game details for: " + steam_id);
                        }
                        return s.redis_client.SETEX(["USER." + steam_id + ".CACHED_APP", s.opts.steam_user_app_cache_validity, s.jsonpack.pack(result)], function(err, result) {});
                      });
                    }
                  } else {
                    if ("function" === typeof callback) {
                      return callback("Error loading user app list from steam");
                    }
                  }
                };
              })(this));
            } else {
              console.log("- return cache for: " + steam_id);
              if ("function" === typeof callback) {
                return callback(null, s.jsonpack.unpack(cached_app_list));
              }
            }
          });
        } else {
          if ("function" === typeof callback) {
            return callback(err, null);
          }
        }
      });
    };

    SteamClient.prototype._push_obj_to_redis = function(root, prefix, obj) {
      var i, key, val, _results;
      if (prefix == null) {
        prefix = "";
      }
      _results = [];
      for (key in obj) {
        val = obj[key];
        if (val instanceof Array) {
          this.redis_client.HSET(root, prefix + ":" + key + ":length", val.length);
          _results.push((function() {
            var _results1;
            _results1 = [];
            for (i in val) {
              _results1.push(this._push_obj_to_redis(root, prefix + ":" + key + ":" + i, 'object' === typeof val[i] ? val[i] : {
                val: val[i]
              }));
            }
            return _results1;
          }).call(this));
        } else if ('object' === typeof val) {
          _results.push(this._push_obj_to_redis(root, prefix + ":" + key, val));
        } else {
          _results.push(this.redis_client.HSET(root, prefix + ":" + key, val));
        }
      }
      return _results;
    };

    SteamClient.prototype._grab_data_from_steam = function() {
      var s;
      s = this;
      return s.redis_client.LRANGE(s.KEYS.STEAM_APP_IDS, 0, -1, function(e, app_list) {
        var batch, i, _results;
        batch = s.opts.n_of_app_in_query_batch;
        i = 0;
        _results = [];
        while (i <= app_list.length) {
          s.unirest.get("http://store.steampowered.com/api/appdetails/").query({
            appids: app_list.slice(i, +(i + batch - 1) + 1 || 9e9).toString()
          }).end((function(_this) {
            return function(response) {
              var app_id, id, item, sdata, _results1;
              sdata = response.body;
              _results1 = [];
              for (app_id in sdata) {
                item = sdata[app_id];
                if (item.success && item.data) {
                  id = parseInt(app_id);
                  item.data._id = id;
                  _results1.push(s.mongo_db.collection(s.KEYS.MDB_STEAM_APPS).update({
                    _id: parseInt(id)
                  }, item.data, {
                    upsert: true
                  }, function(err, count) {
                    return null;
                  }));
                } else {
                  _results1.push(void 0);
                }
              }
              return _results1;
            };
          })(this));
          _results.push(i += batch);
        }
        return _results;
      });
    };

    SteamClient.prototype._read_app_list = function() {
      var s;
      s = this;
      return s.redis_client.GET(s.KEYS.STEAM_APPLIST_RAW, function(e, app_list_raw) {
        var app, steam_apps, _i, _len, _ref;
        s.redis_client.DEL(s.KEYS.STEAM_APP_IDS);
        steam_apps = JSON.parse(app_list_raw);
        _ref = steam_apps.applist.apps.app;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          app = _ref[_i];
          s.redis_client.RPUSH(s.KEYS.STEAM_APP_IDS, app.appid);
        }
        console.log("Start grabbing from Steam");
        return s._grab_data_from_steam();
      });
    };

    SteamClient.prototype._get_app_list = function() {
      var s;
      s = this;
      return s.redis_client.GET(s.KEYS.STEAM_APPLIST_REFRESH, function(err, steam_refresh) {
        return s.redis_client.GET(s.KEYS.STEAM_APPLIST_RAW, function(e, exists) {
          if (steam_refresh && exists) {
            return s._read_app_list();
          } else {
            return s.unirest.get('http://api.steampowered.com/ISteamApps/GetAppList/v0001/').end((function(_this) {
              return function(response) {
                s.redis_client.SET(s.KEYS.STEAM_APPLIST_RAW, response.raw_body);
                s.redis_client.SET(s.KEYS.STEAM_APPLIST_REFRESH, true);
                s.redis_client.EXPIRE(s.KEYS.STEAM_APPLIST_REFRESH, s.opts.steam_app_cache_validity);
                return s._read_app_list();
              };
            })(this));
          }
        });
      });
    };

    return SteamClient;

  })();

}).call(this);
